title: My Blog
description: A blog powered by Jekyll and GitHub Pages.
theme: jekyll-theme-cayman


# Optional: Social links (edit as needed)
social_links:
  - name: GitHub
    url: https://github.com/deepanshu1422
    icon: github

# Plugins (Optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Set URL for your GitHub Pages site (if needed)
url: "https://deepanshu1422.github.io"
baseurl: ""  # Leave it empty for root URL
