title: My Blog
description: A blog powered by Jekyll and GitHub Pages.
theme: minima

# Optional: Social links (edit as needed)
social_links:
  - name: GitHub
    url: https://github.com/deepanshu1422
    icon: github

# Plugins (Optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Set URL for your GitHub Pages site
url: "https://deepanshu1422.github.io"
baseurl: "/blogs"

permalink: /:categories/:title/


# Enable future posts
future: true

# Timezone setting
timezone: UTC

# Add these lines
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
