title: My Tech Journey
description: Exploring computer science, projects, and hackathons
author: Deepanshu
theme: minima

# Social links
twitter_username: your_twitter_handle
github_username:  deepanshu1422
linkedin_username: your_linkedin_profile

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
url: "https://deepanshu1422.github.io"
baseurl: "/blogs"

# Post settings
permalink: /:categories/:title/
future: true

# Timezone setting
timezone: UTC

# Custom settings
show_excerpts: true
header_pages:
  - about.md
  - projects.md
  - contact.md

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
