title: My Blog
description: A blog powered by Jekyll and GitHub Pages.
theme: jekyll-theme-cayman


# Optional: Social links (edit as needed)
social_links:
  - name: GitHub
    url: https://github.com/deepanshu1422
    icon: github

# Plugins (Optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Set URL for your GitHub Pages site (if needed)
url: "https://deepanshu1422.github.io"
baseurl: "/blogs"  # Change this to match your repository name

permalink: /:year/:month/:day/:title/

# Add this line to show future posts (if you want to keep the 2024 date)
# future: true
